### ISSUE TITLE
Security vulnerability: timing attack

### ISSUE THREAD

**Issue by coolaj86** [compwright/x-hub-signature#6]
Checking the signature with `==` allows an attacker to compare timing results between attempts, walking the prefix of the signature until the whole signature is found.

https://github.com/compwright/x-hub-signature/blob/78e3768380c3e522a41748235cfaf3ed0660b283/src/XHubSignature.js#L27

> Using a plain `==` operator is not advised. A method like `secure_compare` performs a "constant time" string comparison, which helps mitigate certain timing attacks against regular equality operators.

https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks

Node provides `crypto.timingSafeEqual(a, b)`.

A runtime-agnostic alternative would be to loop over the string like so:

```js
function verify(a ,b) {
  let count = _verify(a, b,);
  let same = count === 0;
  return same;
}

function _verify(a, b) {
  let count = 0;
  for (let i = 0; i < a.length; i += 1) {
    if (a[i] !== b[i]) {
      count += 1;
    }
  }

  return count;
}
```

There's a possibility that with a pure JavaScript implementation the JIT optimizer will still detect the early return path, causing the timing vulnerability to still exist. That's why I use a count rather than a simple boolean, and run the compare in a separate function. If the optimizer sees that it needs to return the value of count, it should be less likely to short circuit the loop.

**Comment by compwright** [comment]
@coolaj86 thanks for reporting. I'd welcome a pull request on this.

**Comment by G-Rath** [comment]
@compwright since this is a security vulnerability, I'd recommend publishing a [security advisory](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/publishing-a-repository-security-advisory)
